const Banner = require('../models/Banner');
const path = require('path');
const fs = require('fs').promises;

/**
 * Auto-generate banner for Campaign/Coupon/Discount
 * @param {Object} promotion - Campaign, Coupon, or Discount object
 * @param {String} promotionType - 'Campaign', 'Coupon', or 'Discount'
 * @param {String} tenancyId - Tenancy ID
 * @param {String} userId - User ID who created the promotion
 * @returns {Promise<Object>} - Created banner
 */
const autoCreateBanner = async (promotion, promotionType, tenancyId, userId) => {
  try {
    // Generate banner content based on promotion type
    const bannerContent = generateBannerContent(promotion, promotionType);
    
    // Create banner
    const banner = new Banner({
      bannerScope: 'TENANT',
      tenancy: tenancyId,
      title: bannerContent.title,
      description: bannerContent.description,
      imageUrl: bannerContent.imageUrl || '', // Optional - empty string if not provided
      imageAlt: bannerContent.title,
      type: 'PROMOTIONAL',
      linkedPromotion: {
        type: promotionType.toUpperCase(), // Convert to uppercase for enum
        promotionId: promotion._id,
        promotionModel: promotionType
      },
      ctaText: bannerContent.ctaText,
      ctaLink: bannerContent.ctaLink,
      targetPages: ['HOME', 'SERVICES', 'OFFERS'],
      position: 'TOP',
      priority: promotion.priority || 5,
      startDate: promotion.startDate || new Date(),
      endDate: promotion.endDate || new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // 30 days default
      createdBy: userId,
      createdByModel: 'User',
      status: 'DRAFT', // Admin needs to activate
      autoGenerated: true // Mark as auto-generated
    });
    
    await banner.save();
    
    console.log(`✅ Auto-created banner for ${promotionType}: ${promotion.name}`);
    return banner;
  } catch (error) {
    console.error('Auto-create banner error:', error);
    throw error;
  }
};

/**
 * Generate banner content based on promotion details
 */
const generateBannerContent = (promotion, promotionType) => {
  let title, description, ctaText, ctaLink, imageUrl;
  
  // Use a placeholder image service or empty string (will be handled by frontend)
  const defaultImageUrl = 'https://via.placeholder.com/1200x400/4F46E5/FFFFFF?text=';
  
  switch (promotionType) {
    case 'Campaign':
      title = promotion.name || 'Special Campaign';
      description = promotion.description || 'Limited time offer! Don\'t miss out.';
      ctaText = 'View Campaign';
      ctaLink = '/customer/offers';
      imageUrl = defaultImageUrl + encodeURIComponent('Campaign Offer');
      
      // Add discount info to title if available
      if (promotion.promotions && promotion.promotions.length > 0) {
        const firstPromo = promotion.promotions[0];
        if (firstPromo.discountType === 'PERCENTAGE') {
          title = `${title} - ${firstPromo.discountValue}% OFF`;
        } else if (firstPromo.discountType === 'FIXED') {
          title = `${title} - ₹${firstPromo.discountValue} OFF`;
        }
      }
      break;
      
    case 'Coupon':
      title = `Use Code: ${promotion.code}`;
      description = promotion.description || 'Apply this coupon at checkout';
      ctaText = 'Get Coupon';
      ctaLink = '/customer/offers';
      imageUrl = defaultImageUrl + encodeURIComponent('Coupon: ' + (promotion.code || 'Special'));
      
      // Add discount info
      if (promotion.discountType === 'PERCENTAGE') {
        title = `${promotion.discountValue}% OFF - ${promotion.code}`;
      } else if (promotion.discountType === 'FIXED') {
        title = `₹${promotion.discountValue} OFF - ${promotion.code}`;
      }
      break;
      
    case 'Discount':
      title = promotion.name || 'Special Discount';
      description = promotion.description || 'Automatic discount applied at checkout';
      ctaText = 'Shop Now';
      ctaLink = '/customer/services';
      imageUrl = defaultImageUrl + encodeURIComponent('Special Discount');
      
      // Add discount info
      if (promotion.discountType === 'PERCENTAGE') {
        title = `${title} - ${promotion.discountValue}% OFF`;
      } else if (promotion.discountType === 'FIXED') {
        title = `${title} - ₹${promotion.discountValue} OFF`;
      }
      break;
      
    default:
      title = 'Special Offer';
      description = 'Check out our latest promotion';
      ctaText = 'View Offer';
      ctaLink = '/customer/offers';
      imageUrl = defaultImageUrl + encodeURIComponent('Special Offer');
  }
  
  return { title, description, ctaText, ctaLink, imageUrl };
};

/**
 * Update banner when promotion is updated
 */
const updatePromotionBanner = async (promotionId, promotionType, updates) => {
  try {
    // Find banner linked to this promotion
    const banner = await Banner.findOne({
      'linkedPromotion.promotionId': promotionId,
      'linkedPromotion.type': promotionType.toUpperCase(), // Use uppercase for enum
      autoGenerated: true
    });
    
    if (!banner) {
      console.log(`No auto-generated banner found for ${promotionType}: ${promotionId}`);
      return null;
    }
    
    // Update banner fields based on promotion updates
    if (updates.name) {
      const content = generateBannerContent({ ...updates, _id: promotionId }, promotionType);
      banner.title = content.title;
    }
    
    if (updates.description) {
      banner.description = updates.description;
    }
    
    if (updates.startDate) {
      banner.startDate = updates.startDate;
    }
    
    if (updates.endDate) {
      banner.endDate = updates.endDate;
    }
    
    if (updates.status) {
      // Sync banner status with promotion status
      if (updates.status === 'ACTIVE') {
        banner.status = 'ACTIVE';
      } else if (updates.status === 'PAUSED') {
        banner.status = 'PAUSED';
      } else if (updates.status === 'EXPIRED') {
        banner.status = 'EXPIRED';
      }
    }
    
    await banner.save();
    console.log(`✅ Updated banner for ${promotionType}: ${promotionId}`);
    return banner;
  } catch (error) {
    console.error('Update promotion banner error:', error);
    throw error;
  }
};

/**
 * Delete banner when promotion is deleted
 */
const deletePromotionBanner = async (promotionId, promotionType) => {
  try {
    const result = await Banner.deleteOne({
      'linkedPromotion.promotionId': promotionId,
      'linkedPromotion.type': promotionType.toUpperCase(), // Use uppercase for enum
      autoGenerated: true
    });
    
    if (result.deletedCount > 0) {
      console.log(`✅ Deleted banner for ${promotionType}: ${promotionId}`);
    }
    
    return result;
  } catch (error) {
    console.error('Delete promotion banner error:', error);
    throw error;
  }
};

/**
 * Create default banner images if they don't exist
 */
const ensureDefaultBannerImages = async () => {
  try {
    const uploadDir = path.join(process.cwd(), 'public', 'uploads', 'banners');
    await fs.mkdir(uploadDir, { recursive: true });
    
    // Note: In production, you should have actual default images
    // For now, we'll just ensure the directory exists
    console.log('✅ Default banner directory ensured');
  } catch (error) {
    console.error('Ensure default images error:', error);
  }
};

module.exports = {
  autoCreateBanner,
  updatePromotionBanner,
  deletePromotionBanner,
  ensureDefaultBannerImages
};
